name: Build and Release

on:
    push:
        tags:
            - "v*" # Triggers the workflow when pushing a tag that starts with 'v'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14"

            - name: Install Node.js dependencies
              run: npm install

            - name: Sync version across files
              run: npm run sync-version

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "7.4"
                  tools: composer

            - name: Install PHP dependencies
              run: composer install --no-dev --prefer-dist

            - name: Run build script
              run: npm run build

            - name: Debug - List files in build directory
              run: ls -al ./build

            - name: Debug - Check file existence
              run: |
                  if [ ! -f "./build/convoworks-gpt-${{ github.ref_name }}.zip" ]; then
                    echo "Error: File not found!"
                    exit 1
                  fi

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./build/convoworks-gpt-${{ github.ref_name }}.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN instead of GITHUB_TOKEN
